name: Daily Bonpreu Data Fetch

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at 00:00 UTC
  workflow_dispatch:     # Allow manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    env:
      SITEMAP_URL: ${{ secrets.SITEMAP_URL }}
      REQUEST_DURATION_MINUTES: ${{ secrets.REQUEST_DURATION_MINUTES }}
      HTTP_TIMEOUT_SECONDS: ${{ secrets.HTTP_TIMEOUT_SECONDS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_SSL_MODE: ${{ secrets.DB_SSL_MODE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Download dependencies
        run: |
          go mod download
          go mod verify

      - name: Build application
        run: |
          mkdir -p build
          go build -o build/bonpreu-go cmd/bonpreu/main.go

      - name: Run application
        run: |
          ./build/bonpreu-go
